CREATE SEQUENCE student_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE student (
  id NUMBER(19) PRIMARY KEY,
  first_name VARCHAR2(100) NOT NULL,
  last_name  VARCHAR2(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
